library logic
Tresor11/library pull request #1
Opened 2020-03-11 17:04 UTC by Tresor11

2020-03-12 18:07 UTC, bellom requested changes
## Hi Team :clap: 

### Awesome job so far!! :+1: 

#### You have done wonderfully well, you passed `almost` all the checklist for this project :+1: just a few issues left to work on............ :slightly_smiling_face: 
 
### 1. Kindly check out my comments below

### 2. [Optional]
It would be nice to have the `id` of the books in the correct order.
![image](https://user-images.githubusercontent.com/31897434/76552424-15173000-6494-11ea-9eed-1b9a4069f84b.png)

example: 
![image](https://user-images.githubusercontent.com/31897434/76552791-3415c200-6494-11ea-9725-f7f3f3bf56a6.png)


**Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....**

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-03-12 18:07 UTC, bellom commented on .eslintrc.json
> +      "no-unused-vars":"off",
You made some changes in this file, check out the [microverse-linter-config](https://github.com/microverseinc/linters-config/tree/master/javascript)
![image](https://user-images.githubusercontent.com/31897434/73417568-ca44bd00-4318-11ea-8a5e-fedabd629b8c.png)
https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/54883773/

2020-03-12 18:07 UTC, bellom commented on library.js
> +<th scope='row' class='text-center'><span class='badge badge-primary'>${
Kindly fix all indentation in this file.

2020-03-12 18:07 UTC, bellom commented on library.js
> +function render() {
Let have our DOM manipulation task separated from application logic
![image](https://user-images.githubusercontent.com/31897434/76550235-13e50380-6492-11ea-8b09-d8ce72c15c38.png)
https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59623451/

2020-03-12 18:07 UTC, bellom commented on library.js
> +    window.alert('please provide a title');
It is not encouraged to use `alert` in production.
I guess you use `required` on the input tag, with that you don't have to change the linter's config file.

2020-03-12 18:15 UTC, Tresor11 commented on .eslintrc.json
> +      "no-unused-vars":"off",
the linter doesn't allow unused functions however in this case the function add called by the  DOM event

2020-03-12 18:17 UTC, Tresor11 commented on library.js
> +<th scope='row' class='text-center'><span class='badge badge-primary'>${
that was indentation was recommended by the linter

2020-03-12 18:24 UTC, bellom commented on library.js
> +<th scope='row' class='text-center'><span class='badge badge-primary'>${
Looks scattered at my end,  yours?

2020-03-12 18:26 UTC, bellom commented on .eslintrc.json
> +      "no-unused-vars":"off",
In this case, we could use inline come;
`/* eslint-disable no-unused-vars */` 🤔

2020-03-13 09:28 UTC, Tresor11 commented on .eslintrc.json
> +      "no-unused-vars":"off",
thank you for the info we'll be using that :smiley:

2020-03-13 13:36 UTC, Torres-ssf requested changes
### Changes Required :warning: 
Hi there team :hand: 
You did a nice work implementing the requested changes :clap: 
However, it seems you forgot one.

- [x] It's best practice to let the DOM manipulation tasks outside our app logic. You can achieve that by moving the render function to another file and then use export and import to use it. Those concepts were taught in the [ES06 lesson warm up](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/37953388/).
![Screenshot from 2020-03-13 10-29-53](https://user-images.githubusercontent.com/30977845/76625323-bd210d80-6515-11ea-9760-776274adf141.png)

Please kindly submit for code review again after making this change
Happy coding :computer: 
**Sergio Torres**

2020-03-13 20:08 UTC, Tresor11 commented
There is only one Js file because we are not using webpack on this project and thus import/export will not work
Thank you @Torres-ssf  for the precision

2020-03-13 21:20 UTC, shloch approved these changes
## Hello @Tresor11  , @ampaire 
### well done...........all points corrected

![accomplished](https://user-images.githubusercontent.com/40712459/76660281-c98a8200-6578-11ea-83e0-801d5620f7c3.jpg)

### you can merge this

2020-03-13 21:22 UTC, merged